"use client";

type Kind="portfolio"|"github"|"expertise"|"training"|"archive";

const Header=({no,title,status}:{no:string;title:string;status:string})=><div className="mvTop"><span><i>{no}</i> {title}</span><b><i/> {status}</b></div>;

function Portfolio(){return <div className="mockVisual portfolioMock"><Header no="04" title="PORTFOLIO — LIVE SHOWCASE" status="LIVE"/><div className="portfolioStage"><div className="screen s1"><small>01 / CLOUD</small><b>PLATFORM</b><i/><i/><i/></div><div className="screen s2"><small>02 / DELIVERY</small><b>PIPELINE</b><i/><i/><i/></div><div className="screen s3"><small>03 / DATA</small><b>FABRIC</b><i/><i/><i/></div><div className="showcaseAxis"><span>IDEA</span><span>DESIGN</span><span>BUILD</span><span>LIVE</span></div><div className="carouselDots"><i/><i/><i/><i/><i/></div></div></div>}

function Github(){return <div className="mockVisual githubMock"><Header no="05" title="GITHUB — REPOSITORY GRAPH" status="SYNCED"/><div className="gitStage"><div className="gitLabel main">main</div><div className="gitLabel feature">feature</div><svg viewBox="0 0 520 180" preserveAspectRatio="none"><path className="gMain" d="M70 55 H170 C205 55 205 110 240 110 H300 C335 110 335 55 370 55 H455"/><path className="gFeature" d="M70 122 H130 C160 122 160 72 190 72 H250 C285 72 285 122 320 122 H365 C390 122 390 55 420 55"/></svg><div className="commits mainCommits"><i/><i/><i/><i/><i/></div><div className="commits featCommits"><i/><i/><i/><i/></div><div className="mergeBadge">MERGE</div><div className="octo">GH</div><div className="gitWords"><span>CODE</span><span>COLLABORATE</span><span>AUTOMATE</span><span>OPEN SOURCE</span></div></div></div>}

function Expertise(){const nodes=[['AKS','50%','8%'],['Security','78%','23%'],['AI','82%','66%'],['DevOps','72%','83%'],['Fabric','26%','80%'],['Cloud','8%','55%'],['Azure','22%','20%']];return <div className="mockVisual expertiseMock"><Header no="06" title="EXPERTISE — KNOWLEDGE NETWORK" status="INDEXED"/><div className="knowledgeStage"><svg viewBox="0 0 520 180" preserveAspectRatio="none">{nodes.map((n,i)=><line key={n[0]} x1="260" y1="90" x2={[260,405,425,375,135,45,115][i]} y2={[18,48,120,158,155,105,42][i]}/>)}</svg><div className="knowledgeCore"><b>Knowledge</b><small>49 ARTICLES</small></div>{nodes.map((n,i)=><div key={n[0]} className={`knowledgeNode n${i}`}><i/>{n[0]}</div>)}<div className="knowledgeWords"><span>ARTICLES</span><span>CATEGORIES</span><span>TAGS</span><span>EXPLORE</span></div></div></div>}

function Training(){return <div className="mockVisual trainingMock"><Header no="07" title="TRAINING — SKILL TREE" status="GROWING"/><div className="skillStage"><svg viewBox="0 0 520 180" preserveAspectRatio="none"><path d="M260 35V75M260 75L145 118M260 75L375 118M145 118L95 155M145 118L205 155M375 118L315 155M375 118L430 155"/></svg><div className="skillNode root">CLOUD</div><div className="skillNode mid m1">AZURE</div><div className="skillNode mid m2">DATA</div><div className="skillNode leaf l1">NET</div><div className="skillNode leaf l2">AKS</div><div className="skillNode leaf l3">FABRIC</div><div className="skillNode leaf l4">AI</div><div className="skillPulse p1"/><div className="skillPulse p2"/><div className="skillWords"><span>LEARN</span><span>PRACTICE</span><span>APPLY</span><span>MASTER</span></div></div></div>}

function Archive(){return <div className="mockVisual archiveMock"><Header no="08" title="ARCHIVE — DATA VAULT" status="PRESERVED"/><div className="vaultStage"><div className="inputs"><span>DOC</span><span>LOG</span><span>CODE</span><span>NOTE</span></div><svg viewBox="0 0 520 180" preserveAspectRatio="none"><path d="M70 42H135L175 90H235"/><path d="M70 72H125L175 90"/><path d="M70 108H125L175 90"/><path d="M70 138H135L175 90H235"/><path className="vaultFlow" d="M235 90H315"/></svg><div className="indexer"><i/><b>INDEXING...</b></div><div className="vaultCube"><div className="cubeFront"><i/><i/><i/><i/></div><div className="cubeTop"/><div className="cubeSide"/></div><strong className="vaultTitle">DATA VAULT</strong><div className="vaultWords"><span>INGEST</span><span>INDEX</span><span>PRESERVE</span><span>REVISIT</span></div><i className="vaultPacket"/></div></div>}

export default function SystemVisual({kind}:{kind:Kind}){if(kind==="portfolio")return <Portfolio/>;if(kind==="github")return <Github/>;if(kind==="expertise")return <Expertise/>;if(kind==="training")return <Training/>;return <Archive/>}
