"use client";
import { useState } from "react";

export function NeuralSignalLab(){
 const [x,setX]=useState(.8),[w,setW]=useState(1.2),[b,setB]=useState(.1); const z=x*w+b,a=Math.max(0,z),out=1/(1+Math.exp(-(a-.2)));
 return <div className="special-lab"><div className="special-grid"><svg viewBox="0 0 420 250" className="special-svg dl-svg"><line x1="70" y1="125" x2="185" y2="125"/><line x1="225" y1="125" x2="335" y2="125"/><circle cx="55" cy="125" r="25"/><circle className="signal-node" cx="205" cy="125" r="34"/><circle className="output-node" cx="355" cy="125" r="28"/><text x="43" y="130">x</text><text x="187" y="130">ReLU</text><text x="341" y="130">OUT</text><text x="95" y="105">× w={w.toFixed(1)} + b={b.toFixed(1)}</text><text x="110" y="205">z={z.toFixed(2)} → activation={a.toFixed(2)} → output={out.toFixed(2)}</text></svg><div className="special-controls"><h4>NEURAL SIGNAL</h4><label>Input x <input type="range" min="-1" max="1" step=".1" value={x} onChange={e=>setX(+e.target.value)}/><b>{x.toFixed(1)}</b></label><label>Weight w <input type="range" min="-2" max="2" step=".1" value={w} onChange={e=>setW(+e.target.value)}/><b>{w.toFixed(1)}</b></label><label>Bias b <input type="range" min="-1" max="1" step=".1" value={b} onChange={e=>setB(+e.target.value)}/><b>{b.toFixed(1)}</b></label><div className="formula-box">z = xw+b = <strong>{z.toFixed(2)}</strong><br/>ReLU(z) = <strong>{a.toFixed(2)}</strong><br/>신호가 뉴런을 통과하며 어떻게 변하는지 확인하세요.</div></div></div></div>
}

export function WeightUpdateLab(){
 const [w,setW]=useState(2.5),[lr,setLr]=useState(.2); const target=1,grad=2*(w-target),next=w-lr*grad;
 return <div className="special-lab"><div className="special-grid"><svg viewBox="0 0 420 250" className="special-svg dl-svg"><path d="M35 215 Q210 -80 385 215" className="loss-curve"/><circle className="gradient-dot" cx={210+(w-target)*70} cy={215-(w-target)*(w-target)*45} r="9"/><circle className="next-dot" cx={210+(next-target)*70} cy={215-(next-target)*(next-target)*45} r="8"/><text x="25" y="28">Loss=(w−1)²</text><text x="25" y="50">현재 Weight → Gradient → Updated Weight</text></svg><div className="special-controls"><h4>BACKPROP / WEIGHT UPDATE</h4><label>Weight <input type="range" min="-1" max="3" step=".1" value={w} onChange={e=>setW(+e.target.value)}/><b>{w.toFixed(1)}</b></label><label>Learn rate <input type="range" min=".01" max=".8" step=".01" value={lr} onChange={e=>setLr(+e.target.value)}/><b>{lr.toFixed(2)}</b></label><div className="formula-box">∂L/∂w = <strong>{grad.toFixed(2)}</strong><br/>w′ = w − η∇L = <strong>{next.toFixed(2)}</strong><br/>Gradient는 방향, Learning Rate는 이동 크기를 결정합니다.</div></div></div></div>
}

export function OptimizerLab(){
 const [step,setStep]=useState(4); const s=Math.max(0,Math.min(8,step)); const sgd=4*Math.pow(.72,s), mom=4*Math.pow(.58,s)*Math.cos(s*.25), adam=4*Math.pow(.48,s);
 const pos=(v:number)=>210+v*42;
 return <div className="special-lab"><div className="special-grid"><svg viewBox="0 0 440 250" className="special-svg dl-svg"><line x1="30" y1="125" x2="410" y2="125"/><line x1="210" y1="45" x2="210" y2="205"/><circle className="opt-sgd" cx={pos(sgd)} cy="85" r="9"/><circle className="opt-mom" cx={pos(mom)} cy="125" r="9"/><circle className="opt-adam" cx={pos(adam)} cy="165" r="9"/><text x="25" y="88">SGD</text><text x="25" y="128">Momentum</text><text x="25" y="168">Adam</text><text x="190" y="225">OPTIMUM</text></svg><div className="special-controls"><h4>OPTIMIZER RACE</h4><label>Update step <input type="range" min="0" max="8" value={step} onChange={e=>setStep(+e.target.value)}/><b>{step}</b></label><div className="formula-box">SGD distance <strong>{Math.abs(sgd).toFixed(2)}</strong><br/>Momentum distance <strong>{Math.abs(mom).toFixed(2)}</strong><br/>Adam distance <strong>{Math.abs(adam).toFixed(2)}</strong><br/><small>개념적 비교: 실제 궤적은 Loss surface와 gradient에 따라 달라집니다.</small></div></div></div></div>
}

export function ConvolutionLab(){
 const [k,setK]=useState(1); const input=[[1,2,0],[0,3,1],[2,1,2]], kernels=[[[0,1,0],[1,-4,1],[0,1,0]],[[1,0,-1],[1,0,-1],[1,0,-1]],[[1,1,1],[1,1,1],[1,1,1]]]; const names=['Edge','Vertical','Sum']; const ker=kernels[k]; const sum=input.flat().reduce((s,v,i)=>s+v*ker.flat()[i],0);
 return <div className="special-lab"><div className="special-grid"><div className="conv-demo"><div><b>INPUT 3×3</b><div className="pixel-grid">{input.flat().map((v,i)=><span key={i}>{v}</span>)}</div></div><div className="conv-op">×</div><div><b>{names[k]} KERNEL</b><div className="pixel-grid kernel">{ker.flat().map((v,i)=><span key={i}>{v}</span>)}</div></div><div className="conv-op">=</div><div className="conv-result">{sum}</div></div><div className="special-controls"><h4>CONVOLUTION</h4><label>Kernel <input type="range" min="0" max="2" value={k} onChange={e=>setK(+e.target.value)}/><b>{names[k]}</b></label><div className="formula-box">각 위치를 서로 곱한 뒤 모두 더합니다.<br/>Feature value = <strong>{sum}</strong><br/>Kernel이 달라지면 같은 입력에서도 검출되는 특징이 달라집니다.</div></div></div></div>
}

export function RnnLab(){
 const [step,setStep]=useState(0); const xs=[.7,-.2,.9,.4]; let h=0; const hs=xs.map(x=>h=Math.tanh(.8*x+.65*h)); const active=Math.max(0,Math.min(3,step));
 return <div className="special-lab"><div className="special-grid"><div className="rnn-timeline">{xs.map((x,i)=><div className={i===active?'active':''} key={i}><span>x{i+1}<b>{x}</b></span><i>→</i><span>h{i+1}<b>{hs[i].toFixed(2)}</b></span></div>)}</div><div className="special-controls"><h4>RNN HIDDEN STATE</h4><label>Time step <input type="range" min="0" max="3" value={step} onChange={e=>setStep(+e.target.value)}/><b>t{step+1}</b></label><div className="formula-box">hₜ = tanh(0.8xₜ + 0.65hₜ₋₁)<br/>현재 h = <strong>{hs[active].toFixed(3)}</strong><br/>이전 상태가 다음 시점으로 전달되는 것을 따라가세요.</div></div></div></div>
}
