"use client";
import { useMemo, useState } from "react";

function NextTokenLab(){
  const [temperature,setTemperature]=useState(1); const [topK,setTopK]=useState(5); const [step,setStep]=useState(0);
  const vocab=[['learning',2.5],['model',2.0],['AI',1.65],['data',1.2],['system',.8],['banana',-.3]] as const;
  const probs=useMemo(()=>{const ex=vocab.map(([w,l])=>[w,Math.exp(l/temperature)] as const); const sorted=[...ex].sort((a,b)=>b[1]-a[1]).slice(0,topK); const sum=sorted.reduce((a,b)=>a+b[1],0); return sorted.map(([w,v])=>[w,v/sum] as const)},[temperature,topK]);
  const chosen=probs[step%probs.length]?.[0] ?? probs[0][0];
  return <div className="special-lab"><div className="special-grid"><div className="token-generation"><div className="generation-prompt">Neural networks can <strong>{chosen}</strong></div><div className="probability-list">{probs.map(([w,p])=><div key={w}><span>{w}</span><i style={{width:`${p*100}%`}}/><b>{(p*100).toFixed(1)}%</b></div>)}</div></div><div className="special-controls"><h4>NEXT TOKEN SAMPLER</h4><label>Temperature <input type="range" min="0.3" max="2" step="0.1" value={temperature} onChange={e=>setTemperature(+e.target.value)}/><b>{temperature.toFixed(1)}</b></label><label>Top-K <input type="range" min="1" max="6" value={topK} onChange={e=>{setTopK(+e.target.value);setStep(0)}}/><b>{topK}</b></label><button type="button" className="lab-step-button" onClick={()=>setStep(s=>s+1)}>SAMPLE NEXT</button><div className="formula-box">logits ÷ T → Softmax → Top-K → Sample<br/><small>Temperature가 높을수록 분포가 평평해지고 선택 다양성이 커집니다. 이 Lab은 생성 원리를 설명하는 결정론적 시각화입니다.</small></div></div></div></div>
}
function ContextWindowLab(){const [tokens,setTokens]=useState(8); const all=['SYSTEM','Explain','why','attention','helps','a','language','model','understand','long','context','please']; return <div className="special-lab"><div className="special-grid"><div className="context-window">{all.map((t,i)=><span className={i>=all.length-tokens?'inside':'outside'} key={t+i}>{t}<small>#{120+i}</small></span>)}</div><div className="special-controls"><h4>CONTEXT WINDOW</h4><label>Visible tokens <input type="range" min="3" max="12" value={tokens} onChange={e=>setTokens(+e.target.value)}/><b>{tokens}</b></label><div className="formula-box">Window = 최근 <strong>{tokens}</strong> tokens<br/><small>모델은 현재 추론 요청에서 Context Window 안에 제공된 Token을 Attention 대상으로 사용할 수 있습니다.</small></div></div></div></div>}
function TrainingAlignmentLab(){const [stage,setStage]=useState(1); const stages=[['PRETRAIN','대규모 텍스트에서 다음 Token 패턴 학습'],['SFT','Instruction → Response 예제로 행동 조정'],['PREFERENCE','응답 간 선호 신호 수집'],['ALIGN','선호/정책에 맞도록 추가 최적화'],['EVALUATE','품질·안전·회귀 평가']]; return <div className="special-lab"><div className="special-grid"><div className="alignment-flow">{stages.map((s,i)=><button type="button" onClick={()=>setStage(i)} className={i===stage?'active':i<stage?'passed':''} key={s[0]}><b>{s[0]}</b><span>{s[1]}</span></button>)}</div><div className="special-controls"><h4>TRAINING → ALIGNMENT</h4><label>Stage <input type="range" min="0" max="4" value={stage} onChange={e=>setStage(+e.target.value)}/><b>{stage+1}/5</b></label><div className="formula-box"><strong>{stages[stage][0]}</strong><br/>{stages[stage][1]}<br/><small>모든 모델이 정확히 동일한 파이프라인을 사용하는 것은 아니며, 대표적인 개념 흐름입니다.</small></div></div></div></div>}
function VectorSearchLab(){const [qx,setQx]=useState(42),[qy,setQy]=useState(42),[k,setK]=useState(3); const docs=[['AI',28,35],['ML',39,55],['RAG',56,31],['Cloud',77,70],['Recipe',15,82],['Agent',65,44]] as const; const ranked=useMemo(()=>docs.map(d=>({...d,dist:Math.hypot(d[1]-qx,d[2]-qy)})).sort((a,b)=>a.dist-b.dist),[qx,qy]); return <div className="special-lab"><div className="special-grid"><div className="vector-search-space"><div className="query-dot" style={{left:`${qx}%`,top:`${qy}%`}}>Q</div>{docs.map((d)=><div className={ranked.slice(0,k).some(r=>r[0]===d[0])?'doc-dot selected':'doc-dot'} style={{left:`${d[1]}%`,top:`${d[2]}%`}} key={d[0]}>{d[0]}</div>)}</div><div className="special-controls"><h4>VECTOR TOP-K SEARCH</h4><label>Query X <input type="range" min="5" max="90" value={qx} onChange={e=>setQx(+e.target.value)}/><b>{qx}</b></label><label>Query Y <input type="range" min="5" max="90" value={qy} onChange={e=>setQy(+e.target.value)}/><b>{qy}</b></label><label>Top-K <input type="range" min="1" max="5" value={k} onChange={e=>setK(+e.target.value)}/><b>{k}</b></label><div className="search-ranking">{ranked.slice(0,k).map((r,i)=><div key={r[0]}><b>#{i+1} {r[0]}</b><span>distance {r.dist.toFixed(1)}</span></div>)}</div></div></div></div>}
export default function LlmVectorLabs({code}:{code:string}){if(code.startsWith('13.')||['14.09','14.10','14.11','14.12','14.13','14.14','14.15','14.16'].includes(code)) return <NextTokenLab/>; if(['14.07','14.08'].includes(code)) return <ContextWindowLab/>; if(code.startsWith('15.')) return <TrainingAlignmentLab/>; if(code.startsWith('16.')) return <VectorSearchLab/>; return null;}
