
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const base="../../../"; let manifest={documents:[]}, current=null, markdown="", gameJson=null, validation=[];
const stateKey="cheonryugwan-workspace-v0995";
const esc=s=>String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");
function download(name,text,type="text/plain;charset=utf-8"){const b=new Blob([text],{type}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function cards(items){return items.map(([a,b])=>`<div class="summary-card"><span>${esc(a)}</span><strong>${esc(b)}</strong></div>`).join("")}
async function loadManifest(){try{manifest=await fetch("../manifest.json",{cache:"no-store"}).then(r=>r.json())}catch{manifest={documents:[]}} renderDocs()}
function docs(){return manifest.documents||manifest.items||manifest.manuscripts||[]}
function renderDocs(){const q=$("#doc-search").value.toLowerCase(),st=$("#status-filter").value;$("#document-list").innerHTML=docs().filter(d=>(st==="all"||((d.status||"published")===st))&&`${d.title||""} ${d.file||d.path||""}`.toLowerCase().includes(q)).map((d,i)=>`<button class="doc-item" data-i="${i}"><strong>${esc(d.title||d.file||d.path||"Untitled")}</strong><small>${esc(d.file||d.path||"")} · ${esc(d.status||"published")}</small></button>`).join("")||'<p class="help">표시할 문서가 없습니다.</p>';$$(".doc-item").forEach(b=>b.onclick=()=>selectDoc(+b.dataset.i))}
function pathOf(d){let p=d.file||d.path||d.url||"";if(!p)return"";if(p.startsWith("../")||p.startsWith("./"))return p;return "../"+p}
async function selectDoc(i){current=docs()[i];if(!current)return;$$(".doc-item").forEach((b,n)=>b.classList.toggle("active",n===i));$("#current-doc-title").textContent=current.title||current.file||"원본";$("#current-doc-meta").textContent=`${current.status||"published"} · ${current.file||current.path||""}`;try{markdown=await fetch(pathOf(current),{cache:"no-store"}).then(r=>{if(!r.ok)throw Error(r.status);return r.text()})}catch(e){markdown=`# ${current.title||"원본"}\n\n> 원문 로드 실패: ${e.message}`};$("#original-preview").textContent=markdown;$("#workspace-markdown").value=markdown;renderMd();saveState()}
function renderMd(){markdown=$("#workspace-markdown").value;let h=esc(markdown).replace(/^### (.+)$/gm,"<h3>$1</h3>").replace(/^## (.+)$/gm,"<h2>$1</h2>").replace(/^# (.+)$/gm,"<h1>$1</h1>").replace(/^> (.+)$/gm,"<blockquote>$1</blockquote>").replace(/\*\*(.+?)\*\*/g,"<strong>$1</strong>").replace(/\n\n/g,"</p><p>").replace(/\n/g,"<br>");$("#markdown-preview").innerHTML=`<p>${h}</p>`}
function parseFilename(name){const m=name.match(/(\d+)권[-_ ]?(\d+)부/);return{volume:m?+m[1]:null,part:m?+m[2]:null}}
function titleFromMd(md,name){const m=md.match(/^#\s+(.+)$/m);return m?m[1].trim():name.replace(/\.md$/i,"")}
function analyzeMd(md){return{chars:md.replace(/\s/g,"").length,paragraphs:md.split(/\n\s*\n/).filter(x=>x.trim()).length,chapters:(md.match(/^#{1,3}\s+.*(?:장|화)/gm)||[]).length,dialogues:(md.match(/[“"][^”"\n]+[”"]/g)||[]).length}}
function convert(){
 markdown=$("#workspace-markdown").value;const lines=markdown.split(/\n+/).map(x=>x.trim()).filter(x=>x&&!x.startsWith("#")&&!x.startsWith("> Version")&&!/^---+$/.test(x));let scenes=[],n=1,lastSpeaker="";
 for(const line of lines){let speaker="",text=line;let m=line.match(/^([^:：]{1,20})[:：]\s*(.+)$/);if(m){speaker=m[1].replace(/^[-*]\s*/,"").trim();text=m[2].trim();lastSpeaker=speaker}else{m=line.match(/^([^“"]{1,20})[“"](.+)[”"]$/);if(m){speaker=m[1].trim();text=m[2].trim();lastSpeaker=speaker}}
  scenes.push({id:`c01-s${String(n++).padStart(3,"0")}`,speaker,text});}
 if(scenes.length)scenes[scenes.length-1].end=true;const fn=current?.file||$("#new-file-name").value||"workspace.md",meta=parseFilename(fn),title=titleFromMd(markdown,fn);
 gameJson={id:`volume-${String(meta.volume||1).padStart(2,"0")}-part-${String(meta.part||1).padStart(2,"0")}`,title,status:"generated",canon:"source-based",scenes,engineVersion:"0.9.9.5",playMode:"linear",choices:false};
 const a=analyzeMd(markdown);$("#converter-summary").innerHTML=cards([["글자",a.chars],["문단",a.paragraphs],["Scene",scenes.length],["대사 추정",scenes.filter(s=>s.speaker).length]]);$("#json-preview").textContent=JSON.stringify(gameJson,null,2);updateSceneSummary();validateAll();stats();saveState()
}
function updateSceneSummary(){const s=gameJson?.scenes||[];$("#scene-summary").innerHTML=cards([["Scene",s.length],["대사",s.filter(x=>x.speaker).length],["나레이션",s.filter(x=>!x.speaker).length],["CG",s.filter(x=>x.cg||x.cgId).length]]);$("#preview-summary").innerHTML=cards([["Scene",s.length],["Character",s.filter(x=>x.character).length],["Background",s.filter(x=>x.background).length],["Audio",s.filter(x=>x.bgm||x.ambient||x.sfx).length]])}
function validateAll(){
 validation=[];if(!markdown.trim())validation.push(["error","Markdown 본문이 비어 있습니다."]);if(gameJson){const ids=new Set();gameJson.scenes.forEach((s,i)=>{if(!s.id)validation.push(["error",`${i+1}번 Scene ID 없음`]);else if(ids.has(s.id))validation.push(["error",`중복 Scene ID: ${s.id}`]);ids.add(s.id);if(!s.text)validation.push(["warn",`${s.id}: text 없음`]);if(s.character&&!s.speaker)validation.push(["error",`${s.id}: 대사 없는 Scene에 Character 지정`]);if((s.cg||s.cgId)&&s.character)validation.push(["error",`${s.id}: CG와 Character 동시 지정`])})}else validation.push(["warn","게임 JSON이 아직 생성되지 않았습니다."]);
 const e=validation.filter(x=>x[0]==="error").length,w=validation.filter(x=>x[0]==="warn").length;$("#validation-summary").innerHTML=cards([["Error",e],["Warning",w],["Status",e?"FAIL":"PASS"]]);$("#validation-list").innerHTML=validation.length?validation.map(x=>`<div class="validation-item ${x[0]}">${esc(x[1])}</div>`).join(""):'<div class="validation-item ok">현재 Workspace 기본 규칙 검사 PASS</div>';return{e,w}
}
function stats(){
 const s=gameJson?.scenes||[],speakers={},bg={},cg={},chars={};s.forEach(x=>{if(x.speaker)speakers[x.speaker]=(speakers[x.speaker]||0)+1;if(x.background)bg[x.background]=(bg[x.background]||0)+1;if(x.cg||x.cgId){let k=x.cg||x.cgId;cg[k]=(cg[k]||0)+1}if(x.character?.id)chars[x.character.id]=(chars[x.character.id]||0)+1});
 const charsCount=$("#workspace-markdown").value.replace(/\s/g,"").length,minutes=Math.max(1,Math.round(charsCount/350));$("#stats-cards").innerHTML=cards([["Scene",s.length],["글자",charsCount],["예상 플레이",`${minutes}분`],["화자",Object.keys(speakers).length],["배경",Object.keys(bg).length],["CG",Object.keys(cg).length]]);
 $("#speaker-stats").innerHTML=Object.entries(speakers).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="stat-row"><span>${esc(k)}</span><strong>${v}</strong></div>`).join("")||'<p class="help">대사 데이터 없음</p>';
 const assets={...bg,...cg,...chars};$("#asset-stats").innerHTML=Object.entries(assets).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="stat-row"><span>${esc(k)}</span><strong>${v}</strong></div>`).join("")||'<p class="help">Asset 매핑 없음</p>'
}
function manifestEntry(){const fn=current?.file||$("#new-file-name").value||"new.md",p=parseFilename(fn),a=analyzeMd($("#workspace-markdown").value);return{file:fn,title:titleFromMd($("#workspace-markdown").value,fn),volume:p.volume,part:p.part,status:current?.status||$("#new-status").value||"draft",characters:a.chars,paragraphs:a.paragraphs,chapterCount:a.chapters,versionNote:"workspace-v0.9.9.5"}}
function report(){const v=validateAll();return `# Validation Report\n\n- Version: 0.9.9.5\n- Error: ${v.e}\n- Warning: ${v.w}\n\n${validation.map(x=>`- [${x[0].toUpperCase()}] ${x[1]}`).join("\n")||"- PASS"}`}
function usedAssets(){const s=gameJson?.scenes||[];return JSON.stringify({backgrounds:[...new Set(s.map(x=>x.background).filter(Boolean))],characters:[...new Set(s.map(x=>x.character?.id).filter(Boolean))],cg:[...new Set(s.map(x=>x.cg||x.cgId).filter(Boolean))],bgm:[...new Set(s.map(x=>x.bgm).filter(Boolean))],ambient:[...new Set(s.map(x=>x.ambient).filter(Boolean))],sfx:[...new Set(s.map(x=>x.sfx).filter(Boolean))]},null,2)}
function saveState(){localStorage.setItem(stateKey,JSON.stringify({current,markdown:$("#workspace-markdown")?.value||markdown,gameJson,step:$(".step-panel.active")?.id}))}
function restore(){try{const s=JSON.parse(localStorage.getItem(stateKey));if(!s)return;if(s.current)current=s.current;if(s.markdown){markdown=s.markdown;$("#workspace-markdown").value=markdown;$("#original-preview").textContent=markdown;renderMd()}if(s.gameJson){gameJson=s.gameJson;$("#json-preview").textContent=JSON.stringify(gameJson,null,2);updateSceneSummary();validateAll();stats()}}catch{}}
function step(name){$$(".step-panel").forEach(x=>x.classList.toggle("active",x.id===`step-${name}`));$$(".pipeline button").forEach(x=>x.classList.toggle("active",x.dataset.step===name));saveState()}
$$(".pipeline button").forEach(b=>b.onclick=()=>step(b.dataset.step));$$("[data-open]").forEach(b=>b.onclick=()=>location.href=b.dataset.open);
$("#doc-search").oninput=renderDocs;$("#status-filter").onchange=renderDocs;$("#refresh-manifest").onclick=loadManifest;$("#preview-md").onclick=()=>{renderMd();saveState()};$("#workspace-markdown").oninput=()=>{markdown=$("#workspace-markdown").value};
$("#workspace-convert").onclick=convert;$("#send-converter").onclick=()=>{localStorage.setItem("scenario-converter-input",$("#workspace-markdown").value);location.href="../converter/"};
$("#send-scene-editor").onclick=$("#launch-scene-editor").onclick=()=>{if(!gameJson)convert();localStorage.setItem("scene-editor-input",JSON.stringify(gameJson));location.href="../scene-editor/"};
$("#launch-game-preview").onclick=()=>{if(!gameJson)convert();localStorage.setItem("game-preview-input",JSON.stringify(gameJson));location.href="../game-preview/"};
$("#run-validation").onclick=$("#validation-refresh").onclick=()=>{validateAll();step("validation")};$("#stats-refresh").onclick=stats;
$("#create-md").onclick=()=>{const fn=$("#new-file-name").value.trim()||"새-원본.md";current={file:fn,status:$("#new-status").value,title:fn.replace(/\.md$/,"")};markdown=`# ${current.title}\n\n`;$("#workspace-markdown").value=markdown;$("#original-preview").textContent=markdown;renderMd();step("editor");saveState()};
$("#import-md").onclick=()=>$("#import-md-file").click();$("#import-md-file").onchange=async e=>{const f=e.target.files[0];if(!f)return;current={file:f.name,status:$("#new-status").value,title:f.name.replace(/\.md$/,"")};markdown=await f.text();$("#workspace-markdown").value=markdown;$("#original-preview").textContent=markdown;renderMd();step("editor");saveState()};
$("#download-md").onclick=$("#export-md").onclick=()=>download(current?.file||"scenario.md",$("#workspace-markdown").value,"text/markdown;charset=utf-8");
$("#download-json").onclick=$("#export-json").onclick=()=>{if(!gameJson)convert();download(`${gameJson.id||"scenario"}.json`,JSON.stringify(gameJson,null,2),"application/json")};
$("#export-manifest").onclick=()=>download("manifest-entry.json",JSON.stringify(manifestEntry(),null,2),"application/json");$("#export-validation").onclick=()=>download("validation-report.md",report(),"text/markdown;charset=utf-8");$("#export-assets").onclick=()=>download("used-assets.json",usedAssets(),"application/json");
$("#export-summary").onclick=()=>download("workspace-summary.md",`# Workspace Summary\n\n- Document: ${current?.file||"-"}\n- Title: ${titleFromMd($("#workspace-markdown").value,current?.file||"")}\n- Scenes: ${gameJson?.scenes?.length||0}\n- Version: 0.9.9.5\n`,"text/markdown;charset=utf-8");
$("#save-session").onclick=()=>{saveState();alert("브라우저에 Workspace 작업 상태를 저장했습니다.")};$("#new-work").onclick=()=>{if(confirm("현재 Workspace 상태를 초기화할까요?")){localStorage.removeItem(stateKey);location.reload()}};
$("#open-module").onclick=()=>{const n=$(".step-panel.active").id.replace("step-",""),map={viewer:"../viewer.html",editor:"../editor/",converter:"../converter/","scene-editor":"../scene-editor/","game-preview":"../game-preview/"};if(map[n])location.href=map[n]};
$("#export-package").onclick=()=>{const payload={version:"0.9.9.5",manifest:manifestEntry(),markdown:$("#workspace-markdown").value,gameJson,validation:report(),usedAssets:JSON.parse(usedAssets())};download("scenario-workspace-export.json",JSON.stringify(payload,null,2),"application/json")};
loadManifest().then(()=>{restore();step("viewer");stats();validateAll()});
