
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let data={items:[]},category="all",selected=null;
const labels={factions:"세력",martial:"무공·경지",places:"장소",concepts:"핵심 개념",timeline:"연표"};
const esc=s=>String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");
async function init(){data=await fetch("../../data/world-bible.json").then(r=>r.json());render();const hash=location.hash.slice(1);if(hash){const x=data.items.find(i=>i.id===hash);if(x)show(x.id)}}
function filtered(){const q=$("#world-search").value.trim().toLowerCase();return data.items.filter(x=>(category==="all"||x.category===category)&&`${x.title} ${x.subtitle} ${x.summary} ${(x.tags||[]).join(" ")}`.toLowerCase().includes(q))}
function render(){const items=filtered();$("#world-summary").innerHTML=`<span class="summary-pill">소설 기반 ${data.items.length}개 설정</span><span class="summary-pill">현재 ${items.length}개 표시</span><span class="summary-pill">1권 1~4부 출처 연결</span>`;$("#world-grid").innerHTML=items.length?items.map(x=>`<button class="world-card${selected===x.id?" selected":""}" data-id="${x.id}"><span class="category">${labels[x.category]||x.category}</span><h2>${esc(x.title)}</h2><div class="subtitle">${esc(x.subtitle)}</div><p>${esc(x.summary)}</p><div class="tag-list">${(x.tags||[]).slice(0,5).map(t=>`<span class="tag">${esc(t)}</span>`).join("")}</div></button>`).join(""):'<div class="no-results">검색 조건에 맞는 설정이 없습니다.</div>';$$(".world-card").forEach(b=>b.onclick=()=>show(b.dataset.id))}
function show(id){const x=data.items.find(i=>i.id===id);if(!x)return;selected=id;location.hash=id;render();$("#world-detail").innerHTML=`<span class="category">${labels[x.category]||x.category}</span><h2>${esc(x.title)}</h2><div class="detail-subtitle">${esc(x.subtitle)}</div><p>${esc(x.summary)}</p><ul>${(x.details||[]).map(d=>`<li>${esc(d)}</li>`).join("")}</ul><div class="tag-list">${(x.tags||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join("")}</div><div class="source-block"><strong>원본 소설 출처</strong><p>아래 링크는 해당 설정을 구성한 원본 1권 파트입니다.</p><div class="source-links">${(x.sourceParts||[]).map(p=>`<a href="../manuscript/viewer.html?id=volume-01-part-${String(p).padStart(2,"0")}">1권-${p}부 원문 →</a>`).join("")}</div></div>`;if(innerWidth<1050)$("#world-detail").scrollIntoView({behavior:"smooth",block:"start"})}
$("#world-search").oninput=render;$$(".world-filter").forEach(b=>b.onclick=()=>{category=b.dataset.category;$$(".world-filter").forEach(x=>x.classList.toggle("active",x===b));render()});
init().catch(e=>{$("#world-grid").innerHTML=`<div class="no-results">세계관 데이터를 불러오지 못했습니다: ${esc(e.message)}</div>`});
